@https://swordfish-production.up.railway.app/alerts/user_2VqFOsEjFG0YgEAhZDvFe4QE6yf?dropNotificationsCursor=1747189832000-0&limitChangeNotificationsCursor=1738003586901-0&openingLineNotificationsCursor=1739451647372-1 

{
    "data": [
        {
            "id": "1747190108966-0",
            "sportId": "3",
            "minDropPercent": "14",
            "timeIntervalMs": "300000",
            "maxTimeToMatchStartMs": "36000000",
            "lowerBoundOdds": "1.5",
            "upperBoundOdds": "3",
            "nickname": "Basketball(>5H)",
            "includeMoneyline": "1",
            "includeSpreads": "1",
            "includeTotals": "1",
            "percentageChange": "16.39024390243902",
            "changeFrom": "2.05",
            "changeTo": "1.714",
            "eventId": "1609615351",
            "periodNumber": "0",
            "lineType": "spread",
            "points": "8",
            "outcome": "home",
            "timestamp": "1747190108910",
            "leagueName": "Philippines - PBA Philippines Cup",
            "home": "Meralco Bolts",
            "away": "Timplados Hotshots",
            "noVigPrice": "",
            "starts": "1747222200000",
            "type": "oddsDrop",
            "alertingCriteriaId": "alertingCriteria:evgebfbeq2191dq8qs7h7xpv",
            "userId": "user_2VqFOsEjFG0YgEAhZDvFe4QE6yf",
            "lowerBoundLimit": "150",
            "upperBoundLimit": "1000000",
            "includeOrExcludeCompetitions": "include",
            "enabled": "1",
            "changeDirection": "increase",
            "includePeriod0": "1",
            "includePeriod1": "1",
            "priceHome": "1.714",
            "priceAway": "1.925"
        },
        {
            "id": "1747190108966-1",
            "sportId": "3",
            "minDropPercent": "14",
            "timeIntervalMs": "300000",
            "maxTimeToMatchStartMs": "36000000",
            "lowerBoundOdds": "1.5",
            "upperBoundOdds": "3",
            "nickname": "Basketball(>5H)",
            "includeMoneyline": "1",
            "includeSpreads": "1",
            "includeTotals": "1",
            "percentageChange": "16.30541871921181",
            "changeFrom": "2.03",
            "changeTo": "1.699",
            "eventId": "1609615351",
            "periodNumber": "0",
            "lineType": "total",
            "points": "195",
            "outcome": "under",
            "timestamp": "1747190108910",
            "leagueName": "Philippines - PBA Philippines Cup",
            "home": "Meralco Bolts",
            "away": "Timplados Hotshots",
            "noVigPrice": "",
            "starts": "1747222200000",
            "type": "oddsDrop",
            "alertingCriteriaId": "alertingCriteria:evgebfbeq2191dq8qs7h7xpv",
            "userId": "user_2VqFOsEjFG0YgEAhZDvFe4QE6yf",
            "lowerBoundLimit": "150",
            "upperBoundLimit": "1000000",
            "includeOrExcludeCompetitions": "include",
            "enabled": "1",
            "changeDirection": "increase",
            "includePeriod0": "1",
            "includePeriod1": "1",
            "priceOver": "1.952",
            "priceUnder": "1.699"
        },
        {
            "id": "1747190156941-0",
            "sportId": "3",
            "minDropPercent": "14",
            "timeIntervalMs": "300000",
            "maxTimeToMatchStartMs": "36000000",
            "lowerBoundOdds": "1.5",
            "upperBoundOdds": "3",
            "nickname": "Basketball(>5H)",
            "includeMoneyline": "1",
            "includeSpreads": "1",
            "includeTotals": "1",
            "percentageChange": "16.146341463414622",
            "changeFrom": "2.05",
            "changeTo": "1.719",
            "eventId": "1609615351",
            "periodNumber": "0",
            "lineType": "spread",
            "points": "8",
            "outcome": "home",
            "timestamp": "1747190156886",
            "leagueName": "Philippines - PBA Philippines Cup",
            "home": "Meralco Bolts",
            "away": "Timplados Hotshots",
            "noVigPrice": "",
            "starts": "1747222200000",
            "type": "oddsDrop",
            "alertingCriteriaId": "alertingCriteria:evgebfbeq2191dq8qs7h7xpv",
            "userId": "user_2VqFOsEjFG0YgEAhZDvFe4QE6yf",
            "lowerBoundLimit": "150",
            "upperBoundLimit": "1000000",
            "includeOrExcludeCompetitions": "include",
            "enabled": "1",
            "changeDirection": "increase",
            "includePeriod0": "1",
            "includePeriod1": "1",
            "priceHome": "1.719",
            "priceAway": "1.925"
        },
        {
            "id": "1747190210978-0",
            "sportId": "3",
            "minDropPercent": "14",
            "timeIntervalMs": "300000",
            "maxTimeToMatchStartMs": "36000000",
            "lowerBoundOdds": "1.5",
            "upperBoundOdds": "3",
            "nickname": "Basketball(>5H)",
            "includeMoneyline": "1",
            "includeSpreads": "1",
            "includeTotals": "1",
            "percentageChange": "16.146341463414622",
            "changeFrom": "2.05",
            "changeTo": "1.719",
            "eventId": "1609615351",
            "periodNumber": "0",
            "lineType": "spread",
            "points": "8",
            "outcome": "home",
            "timestamp": "1747190210930",
            "leagueName": "Philippines - PBA Philippines Cup",
            "home": "Meralco Bolts",
            "away": "Timplados Hotshots",
            "noVigPrice": "",
            "starts": "1747222200000",
            "type": "oddsDrop",
            "alertingCriteriaId": "alertingCriteria:evgebfbeq2191dq8qs7h7xpv",
            "userId": "user_2VqFOsEjFG0YgEAhZDvFe4QE6yf",
            "lowerBoundLimit": "150",
            "upperBoundLimit": "1000000",
            "includeOrExcludeCompetitions": "include",
            "enabled": "1",
            "changeDirection": "increase",
            "includePeriod0": "1",
            "includePeriod1": "1",
            "priceHome": "1.719",
            "priceAway": "1.925"
        },
        {
            "id": "1747190247070-0",
            "sportId": "3",
            "minDropPercent": "14",
            "timeIntervalMs": "300000",
            "maxTimeToMatchStartMs": "36000000",
            "lowerBoundOdds": "1.5",
            "upperBoundOdds": "3",
            "nickname": "Basketball(>5H)",
            "includeMoneyline": "1",
            "includeSpreads": "1",
            "includeTotals": "1",
            "percentageChange": "16.146341463414622",
            "changeFrom": "2.05",
            "changeTo": "1.719",
            "eventId": "1609615351",
            "periodNumber": "0",
            "lineType": "spread",
            "points": "8",
            "outcome": "home",
            "timestamp": "1747190246994",
            "leagueName": "Philippines - PBA Philippines Cup",
            "home": "Meralco Bolts",
            "away": "Timplados Hotshots",
            "noVigPrice": "",
            "starts": "1747222200000",
            "type": "oddsDrop",
            "alertingCriteriaId": "alertingCriteria:evgebfbeq2191dq8qs7h7xpv",
            "userId": "user_2VqFOsEjFG0YgEAhZDvFe4QE6yf",
            "lowerBoundLimit": "150",
            "upperBoundLimit": "1000000",
            "includeOrExcludeCompetitions": "include",
            "enabled": "1",
            "changeDirection": "increase",
            "includePeriod0": "1",
            "includePeriod1": "1",
            "priceHome": "1.719",
            "priceAway": "1.925"
        }
    ]
}